# Deployment with default values
# Cluster Ingress specific values are applied at runtime.
kind: Deployment
apiVersion: apps/v1
metadata:
  # name is set at runtime.
  # namespace is set at runtime.
  labels:
    app: router
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      # serviceAccountName is set at runtime.
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ''
      priorityClassName: system-cluster-critical
      containers:
        - name: router
          # image is set at runtime.
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          - name: stats
            containerPort: 1936
            protocol: TCP
          # Merged at runtime.
          env:
          - name: STATS_PORT
            value: "1936"
          - name: ROUTER_SERVICE_NAMESPACE
            value: openshift-ingress
          - name: DEFAULT_CERTIFICATE_DIR
            value: /etc/pki/tls/private
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthz
              port: 1936
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthz
              port: 1936
          volumeMounts:
          - mountPath: /etc/pki/tls/private
            name: default-certificate
            readOnly: true
      volumes:
      - name: default-certificate
        secret:
          defaultMode: 420
          # SecretName is set at run-time.
